name: Create Release

on:
  push:
    tags:
      - 'v[0-9].*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            bin_name: nimble-linux
            archive_name: nimble-linux.tar.gz
          - os: macos-latest
            bin_name: nimble-macos
            archive_name: nimble-macos.tar.gz
          - os: windows-latest
            bin_name: nimble-windows.exe
            archive_name: nimble-windows.zip

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up C++ environment on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y clang make

      - name: Set up C++ environment on macOS
        if: matrix.os == 'macos-latest'
        run: xcode-select --install || true

      - name: Set up C++ environment on Windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install make
          choco install mingw
        shell: powershell

      - name: Build the project on Linux/macOS
        if: matrix.os != 'windows-latest'
        run: make release

      - name: Build the project on Windows
        if: matrix.os == 'windows-latest'
        run: make release
        shell: bash

      - name: Rename binary on Linux/macOS
        if: matrix.os != 'windows-latest'
        run: mv bin/nimble ${{ matrix.bin_name }}

      - name: Rename binary on Windows
        if: matrix.os == 'windows-latest'
        run: mv bin/nimble ${{ matrix.bin_name }}
        shell: bash

      - name: Archive binary on Linux/macOS
        if: matrix.os != 'windows-latest'
        run: tar -czvf ${{ matrix.archive_name }} ${{ matrix.bin_name }}

      - name: Archive binary on Windows
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path ${{ matrix.bin_name }} -DestinationPath ${{ matrix.archive_name }}
        shell: powershell

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.archive_name }}
          path: ${{ matrix.archive_name }}

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: nimble-linux.tar.gz
          path: .
      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: nimble-macos.tar.gz
          path: .
      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: nimble-windows.zip
          path: .

      - name: Set variables
        id: vars
        run: echo "tag=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: ${{ env.tag }}
          body: |
            NIMBLE release. Version ${{ env.tag }}
          draft: false
          prerelease: false

      - name: Upload Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nimble-linux.tar.gz
          asset_name: nimble-linux.tar.gz
          asset_content_type: application/gzip

      - name: Upload macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nimble-macos.tar.gz
          asset_name: nimble-macos.tar.gz
          asset_content_type: application/gzip

      - name: Upload Windows binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nimble-windows.zip
          asset_name: nimble-windows.zip
          asset_content_type: application/zip
